name: alarm_app
description: "무조건 깨우는 알람 앱"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  alarm: ^5.4.1
  flutter_foreground_task: ^8.13.0
  sensors_plus: ^6.1.0
  audioplayers: ^6.4.0
  flutter_local_notifications: ^18.0.0
  permission_handler: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
